import type { ClusterReport, TriageResult } from '../types.js';

/**
 * Self-contained static HTML triage page: cluster cards grouped by verdict,
 * no external assets, safe to publish as a CI artifact next to the
 * Playwright HTML report.
 */
export function triageHtml(result: TriageResult): string {
  const { stats, reports, synthesis } = result;
  const cards = reports.map(clusterCard).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Triage — ${escapeHtml(stats.runId)}</title>
<style>
  :root { color-scheme: light dark; font-family: system-ui, sans-serif; }
  body { margin: 0 auto; max-width: 60rem; padding: 2rem 1rem; line-height: 1.5; }
  h1 { font-size: 1.4rem; }
  .stats { display: flex; gap: 1rem; flex-wrap: wrap; margin: 1rem 0; }
  .stat { border: 1px solid #8884; border-radius: 8px; padding: .6rem 1rem; }
  .stat b { font-size: 1.3rem; display: block; }
  .synthesis { border-left: 4px solid #8886; padding: .5rem 1rem; margin: 1rem 0; background: #8881; }
  .card { border: 1px solid #8884; border-radius: 8px; padding: 1rem; margin: 1rem 0; }
  .badge { display: inline-block; border-radius: 999px; padding: .1rem .7rem; font-size: .8rem; font-weight: 600; }
  .likely-bug { background: #d3302f22; color: #d3302f; }
  .likely-flaky { background: #b8860b22; color: #b8860b; }
  .infrastructure { background: #1e6fd922; color: #1e6fd9; }
  .unknown { background: #8883; }
  pre { overflow-x: auto; background: #8881; padding: .8rem; border-radius: 6px; font-size: .85rem; }
  .meta { color: #888; font-size: .85rem; }
  ol li, ul li { margin: .15rem 0; }
</style>
</head>
<body>
<h1>Test triage — <code>${escapeHtml(stats.runId)}</code></h1>
<div class="stats">
  <div class="stat"><b>${stats.failed}</b>failed</div>
  <div class="stat"><b>${stats.flaky}</b>flaky</div>
  <div class="stat"><b>${stats.passed}</b>passed</div>
  <div class="stat"><b>${reports.length}</b>root causes</div>
</div>
${
  synthesis
    ? `<div class="synthesis"><p>${escapeHtml(synthesis.summary)}</p><p><b>${
        synthesis.systemicIssue ? '⚠️ Likely systemic issue.' : 'Failures look independent.'
      }</b> ${escapeHtml(synthesis.recommendation)}</p></div>`
    : ''
}
${cards}
<p class="meta">Generated by test-triage-kit.</p>
</body>
</html>
`;
}

function clusterCard(report: ClusterReport): string {
  const { cluster, verdict, history, ai } = report;
  const rep = cluster.representative;
  const title = ai?.title ?? rep.testId;

  return `<div class="card">
  <span class="badge ${verdict.type}">${escapeHtml(verdict.type)}</span>
  <span class="badge unknown">${escapeHtml(cluster.category)}</span>
  ${ai ? `<span class="badge unknown">severity: ${escapeHtml(ai.severity)}</span>` : ''}
  <h2>${escapeHtml(title)}</h2>
  <p class="meta">fingerprint <code>${cluster.fingerprint}</code> · ${cluster.failures.length} occurrence(s) · ${escapeHtml(
    [...new Set(cluster.failures.map((f) => f.project || 'default'))].join(', '),
  )}${
    history && history.runsRecorded > 0
      ? ` · seen in ${history.timesSeen}/${history.runsRecorded} past runs`
      : ''
  }</p>
  <ul>${verdict.reasons.map((r) => `<li>${escapeHtml(r)}</li>`).join('')}</ul>
  ${ai ? `<p><b>Hypothesis:</b> ${escapeHtml(ai.rootCauseHypothesis)}</p>` : ''}
  ${
    ai && ai.reproSteps.length > 0
      ? `<ol>${ai.reproSteps.map((s) => `<li>${escapeHtml(s)}</li>`).join('')}</ol>`
      : ''
  }
  <pre>${escapeHtml(truncate(rep.errorMessage || '(empty error message)', 1500))}</pre>
</div>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function truncate(text: string, max: number): string {
  return text.length > max ? text.slice(0, max) + '…' : text;
}
