import type { ClusterReport, TriageResult } from '../types.js';
import type { AdfDoc, AdfNode } from './jira.js';
import { clusterAdf } from './jira.js';

/**
 * Self-contained static HTML page previewing what the Jira sync would
 * create: real ADF documents (built by clusterAdf) rendered to look like
 * Jira issue cards, so the lifecycle is demonstrable without a live Jira
 * site — the free tier doesn't support public anonymous issue viewing.
 */
export function jiraPreviewHtml(
  result: TriageResult,
  issueKeyPrefix: string,
  illustrations: Record<string, string> = {},
): string {
  const bugs = result.reports.filter((r) => r.verdict.type === 'likely-bug');
  const cards = bugs
    .map((report, i) =>
      issueCard(report, `${issueKeyPrefix}-${i + 1}`, result.stats.runId, illustrations[report.cluster.fingerprint]),
    )
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Jira preview — ${escapeHtml(result.stats.runId)}</title>
<style>
  :root { color-scheme: light dark; font-family: system-ui, sans-serif; }
  body { margin: 0 auto; max-width: 46rem; padding: 2rem 1rem; line-height: 1.5; }
  h1 { font-size: 1.4rem; }
  .meta { color: #888; font-size: .85rem; }
  .issue { border: 1px solid #8884; border-radius: 8px; padding: 1.2rem; margin: 1.2rem 0; }
  .issue-header { display: flex; align-items: center; gap: .6rem; margin-bottom: .8rem; }
  .key { font-family: ui-monospace, monospace; color: #0052cc; font-weight: 600; }
  .type-badge { display: inline-flex; align-items: center; gap: .3rem; background: #de350b22; color: #de350b; border-radius: 4px; padding: .1rem .5rem; font-size: .78rem; font-weight: 600; }
  .label { display: inline-block; background: #8882; border-radius: 3px; padding: .05rem .5rem; font-size: .75rem; margin-right: .3rem; }
  .issue h2 { margin: .3rem 0 .6rem; font-size: 1.1rem; }
  .attachment { margin: .8rem 0; }
  .attachment svg { display: block; width: 100%; height: auto; border: 1px solid #8884; border-radius: 6px; color: #6b6b6b; }
  .attachment figcaption { font-size: .78rem; color: #888; margin-top: .3rem; }
  ul, ol { padding-left: 1.4rem; font-size: .9rem; }
  ul b { color: #6b6b6b; font-weight: 600; }
  h3 { font-size: .95rem; margin: .9rem 0 .3rem; }
  pre { overflow-x: auto; background: #8881; padding: .8rem; border-radius: 6px; font-size: .82rem; }
  ol li, ul li { margin: .15rem 0; }
</style>
</head>
<body>
<h1>Jira preview — <code>${escapeHtml(result.stats.runId)}</code></h1>
<p class="meta">Rendered from the real ADF documents built by <code>output/jira.ts</code> — the exact payload the <code>--jira</code> sync would send. Issue keys (${escapeHtml(issueKeyPrefix)}-N) are illustrative: the free tier of Jira Cloud doesn't support public anonymous issue viewing, so this static render stands in for a live link.</p>
${cards || '<p>No likely-bug verdicts in this run.</p>'}
<p class="meta">Generated by test-triage-kit.</p>
</body>
</html>
`;
}

function issueCard(report: ClusterReport, issueKey: string, runId: string, illustration?: string): string {
  const title = report.ai?.title ?? report.cluster.representative.testId;
  const doc = clusterAdf(report, runId);
  return `<div class="issue">
  <div class="issue-header">
    <span class="key">${escapeHtml(issueKey)}</span>
    <span class="type-badge">🐞 Bug</span>
    <span class="label">automated-triage</span>
  </div>
  <h2>${escapeHtml(title)}</h2>
  ${illustration ? attachmentFigure(illustration) : ''}
  ${adfToHtml(doc)}
</div>`;
}

function attachmentFigure(svg: string): string {
  return `<figure class="attachment">
    ${svg}
    <figcaption>Illustrative reproduction, not a captured screenshot — the demo fixture is synthetic.</figcaption>
  </figure>`;
}

export function adfToHtml(doc: AdfDoc): string {
  return doc.content.map(nodeToHtml).join('\n');
}

function nodeToHtml(node: AdfNode): string {
  switch (node.type) {
    case 'paragraph':
      return `<p>${inlineHtml(node)}</p>`;
    case 'heading':
      return `<h3>${inlineHtml(node)}</h3>`;
    case 'codeBlock':
      return `<pre>${escapeHtml(text(node))}</pre>`;
    case 'bulletList':
      return `<ul>${(node.content ?? []).map(nodeToHtml).join('')}</ul>`;
    case 'orderedList':
      return `<ol>${(node.content ?? []).map(nodeToHtml).join('')}</ol>`;
    case 'listItem':
      return `<li>${(node.content ?? []).map(inlineOrBlock).join('')}</li>`;
    default:
      return '';
  }
}

function inlineOrBlock(node: AdfNode): string {
  return node.type === 'paragraph' ? inlineHtml(node) : nodeToHtml(node);
}

function inlineHtml(node: AdfNode): string {
  const raw = text(node);
  const colonIndex = raw.indexOf(': ');
  if (colonIndex > 0 && colonIndex < 40) {
    return `<b>${escapeHtml(raw.slice(0, colonIndex))}:</b> ${escapeHtml(raw.slice(colonIndex + 2))}`;
  }
  return escapeHtml(raw);
}

function text(node: AdfNode): string {
  if (node.text) return node.text;
  return (node.content ?? []).map(text).join('');
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
