import type { ClusterReport, TriageResult } from '../types.js';

const VERDICT_LABEL: Record<string, string> = {
  'likely-bug': '🐞 Likely application bug',
  'likely-flaky': '🎲 Likely flaky test',
  infrastructure: '🏗️ Infrastructure / environment',
  unknown: '❓ Unclassified',
};

/** One markdown bug report per cluster — also used as the GitHub issue body. */
export function clusterMarkdown(report: ClusterReport, runId: string): string {
  const { cluster, verdict, history, ai } = report;
  const rep = cluster.representative;

  const lines: string[] = [];
  lines.push(`<!-- triage-fingerprint: ${cluster.fingerprint} -->`);
  lines.push(`# ${ai?.title ?? defaultTitle(report)}`);
  lines.push('');
  lines.push(`**Verdict:** ${VERDICT_LABEL[verdict.type] ?? verdict.type}`);
  for (const reason of verdict.reasons) lines.push(`- ${reason}`);
  lines.push('');
  lines.push('| | |');
  lines.push('|---|---|');
  lines.push(`| Category | \`${cluster.category}\` |`);
  lines.push(`| Fingerprint | \`${cluster.fingerprint}\` |`);
  lines.push(`| Occurrences this run | ${cluster.failures.length} |`);
  lines.push(`| Affected tests | ${uniqueTests(report).join('<br>')} |`);
  if (ai) lines.push(`| Proposed severity | **${ai.severity}** — ${ai.severityRationale} |`);
  if (history && history.runsRecorded > 0) {
    lines.push(
      `| History | seen in ${history.timesSeen}/${history.runsRecorded} past runs (${history.consecutiveRunsSeen} consecutive) |`,
    );
  }
  lines.push(`| Run | \`${runId}\` |`);
  lines.push('');

  if (ai) {
    lines.push('## Root cause hypothesis');
    lines.push(ai.rootCauseHypothesis);
    lines.push('');
    lines.push('## Steps to reproduce');
    ai.reproSteps.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
    lines.push('');
  } else if (rep.steps.length > 0) {
    lines.push('## Test steps before failure');
    rep.steps.forEach((step) => lines.push(`- ${step}`));
    lines.push('');
  }

  lines.push('## Error');
  lines.push('```');
  lines.push(truncate(rep.errorMessage || '(empty error message)', 2000));
  lines.push('```');

  if (rep.attachments.length > 0) {
    lines.push('');
    lines.push('## Attachments');
    for (const a of rep.attachments) {
      lines.push(`- ${a.name} (\`${a.contentType}\`)${a.path ? ` — \`${a.path}\`` : ''}`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('_Generated by [test-triage-kit](https://github.com/GabrieleScano/test-triage-kit)._');
  return lines.join('\n');
}

/** Run-level summary (console + markdown file + Slack). */
export function runSummaryMarkdown(result: TriageResult): string {
  const { stats, reports, synthesis } = result;
  const lines: string[] = [];
  lines.push(`# Triage summary — run \`${stats.runId}\``);
  lines.push('');
  lines.push(
    `**${stats.failed} failed**, ${stats.flaky} flaky, ${stats.passed} passed of ${stats.total} tests — ${reports.length} distinct root cause(s).`,
  );
  lines.push('');
  if (synthesis) {
    lines.push(`> ${synthesis.summary}`);
    lines.push('>');
    lines.push(
      `> ${synthesis.systemicIssue ? '⚠️ **Likely systemic issue.**' : 'Failures look independent.'} ${synthesis.recommendation}`,
    );
    lines.push('');
  }
  lines.push('| Verdict | Category | Occurrences | Report |');
  lines.push('|---|---|---|---|');
  for (const report of reports) {
    lines.push(
      `| ${VERDICT_LABEL[report.verdict.type] ?? report.verdict.type} | \`${report.cluster.category}\` | ${report.cluster.failures.length} | \`${reportFileName(report)}\` |`,
    );
  }
  return lines.join('\n');
}

export function defaultTitle(report: ClusterReport): string {
  const rep = report.cluster.representative;
  const firstLine = rep.errorMessage.split('\n').find((l) => l.trim()) ?? rep.testId;
  return `[${report.cluster.category}] ${truncate(firstLine.trim(), 120)}`;
}

export function reportFileName(report: ClusterReport): string {
  return `report-${report.cluster.fingerprint}.md`;
}

function uniqueTests(report: ClusterReport): string[] {
  return [...new Set(report.cluster.failures.map((f) => `\`${f.testId}\``))];
}

function truncate(text: string, max: number): string {
  return text.length > max ? text.slice(0, max) + '…' : text;
}
